### PR TITLE
Fix #7 : Support hyperlinks

### LINKED ISSUE #7: Support hyperlinks
Currently links are just text

### PR DESCRIPTION
**Pull request by joybro**
This fixes issue #7.
hangups.ChatMessageSegment.from_str parses given text and makes link work.

### CODE REVIEW

**Comment by codeallthethingz** [comment]
@joybro awesome! This is our first community patch. 
@ehacke is there a unit test suite for this class and if not can we create one before this is merged?

**Comment by ehacke** [comment]
@joybro thanks! 
@willwarren no unit testing at the moment because 95% of the code came from other places, none of it with unit testing. 

I had planned on looking at the project today, so I'll merge this, test it, and try to get an all-in-one installer built.

**Comment by codeallthethingz** [comment]
OK. But make maidi do it!

**Comment by ehacke** [comment]
@willwarren yup, will do.

**Comment by joybro** [comment]
@ehacke @willwarren I rebased my patch so that it could be merged without conflict.
Thank you for good project. I like hubot-hangups :)

**Comment by ehacke** [comment]
@joybro thanks alot, I was about to mention that. I'll have @l3ubbleman merge it tomorrow morning.

**Comment by ehacke** [comment]
Testing created in separate branch, will merge that next.

**Pull request merged**
